name: Update JSON with Web Scraping

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main 
      
permissions:
  contents: write
  
jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run main
        run: python main.py

      
      - name: Configure git for GitHub Actions
        run: |
          git config --global user.name "bot-daemon"
          git config --global user.email "bot-daemon@example.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/bot-daemon/python-scrapp.git


      - name: Commit and Push Changes
        run: |
          git add data.json
          git commit -m "Update JSON data [skip ci]" || echo "No changes to commit"
          git push